"""add betting_price to market outcomes

Revision ID: c65bd826f20a
Revises: e293f5e365fe
Create Date: 2026-05-17 18:42:55.667424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c65bd826f20a'
down_revision = 'e293f5e365fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_outcomes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('betting_price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_outcomes', schema=None) as batch_op:
        batch_op.drop_column('betting_price')

    # ### end Alembic commands ###
