"""wallet chnages

Revision ID: e293f5e365fe
Revises: b2c3d4e5f6a7
Create Date: 2026-05-17 01:35:16.780117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e293f5e365fe'
down_revision = 'b2c3d4e5f6a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_wallet_address', sa.String(length=42), nullable=True))
        batch_op.add_column(sa.Column('to_wallet_address', sa.String(length=42), nullable=True))
        batch_op.add_column(sa.Column('tx_hash', sa.String(length=66), nullable=True))
        batch_op.add_column(sa.Column('token_id', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('bet_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reference_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_wallet_address'))
        batch_op.create_unique_constraint(None, ['wallet_address'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('ix_users_wallet_address'), ['wallet_address'], unique=True)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('reference_id')
        batch_op.drop_column('bet_id')
        batch_op.drop_column('token_id')
        batch_op.drop_column('tx_hash')
        batch_op.drop_column('to_wallet_address')
        batch_op.drop_column('from_wallet_address')

    # ### end Alembic commands ###
